// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/searchnode/v1/searchnode.proto

package searchnodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TabletRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId     string                 `protobuf:"bytes,3,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabletRef) Reset() {
	*x = TabletRef{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabletRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletRef) ProtoMessage() {}

func (x *TabletRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletRef.ProtoReflect.Descriptor instead.
func (*TabletRef) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{0}
}

func (x *TabletRef) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *TabletRef) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *TabletRef) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type SearchShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tablet        *TabletRef             `protobuf:"bytes,1,opt,name=tablet,proto3" json:"tablet,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchShardRequest) Reset() {
	*x = SearchShardRequest{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchShardRequest) ProtoMessage() {}

func (x *SearchShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchShardRequest.ProtoReflect.Descriptor instead.
func (*SearchShardRequest) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{1}
}

func (x *SearchShardRequest) GetTablet() *TabletRef {
	if x != nil {
		return x.Tablet
	}
	return nil
}

func (x *SearchShardRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchShardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchShardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHit) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Hits          []*SearchHit           `protobuf:"bytes,2,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchShardResponse) Reset() {
	*x = SearchShardResponse{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchShardResponse) ProtoMessage() {}

func (x *SearchShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchShardResponse.ProtoReflect.Descriptor instead.
func (*SearchShardResponse) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{3}
}

func (x *SearchShardResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchShardResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type TabletStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabletStatusRequest) Reset() {
	*x = TabletStatusRequest{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabletStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletStatusRequest) ProtoMessage() {}

func (x *TabletStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletStatusRequest.ProtoReflect.Descriptor instead.
func (*TabletStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{4}
}

type TabletStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tablet         *TabletRef             `protobuf:"bytes,1,opt,name=tablet,proto3" json:"tablet,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State          string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	LastCheckpoint int64                  `protobuf:"varint,4,opt,name=last_checkpoint,json=lastCheckpoint,proto3" json:"last_checkpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TabletStatus) Reset() {
	*x = TabletStatus{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabletStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletStatus) ProtoMessage() {}

func (x *TabletStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletStatus.ProtoReflect.Descriptor instead.
func (*TabletStatus) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{5}
}

func (x *TabletStatus) GetTablet() *TabletRef {
	if x != nil {
		return x.Tablet
	}
	return nil
}

func (x *TabletStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TabletStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TabletStatus) GetLastCheckpoint() int64 {
	if x != nil {
		return x.LastCheckpoint
	}
	return 0
}

type TabletStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tablets       []*TabletStatus        `protobuf:"bytes,1,rep,name=tablets,proto3" json:"tablets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabletStatusResponse) Reset() {
	*x = TabletStatusResponse{}
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabletStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletStatusResponse) ProtoMessage() {}

func (x *TabletStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_searchnode_v1_searchnode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletStatusResponse.ProtoReflect.Descriptor instead.
func (*TabletStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_searchnode_v1_searchnode_proto_rawDescGZIP(), []int{6}
}

func (x *TabletStatusResponse) GetTablets() []*TabletStatus {
	if x != nil {
		return x.Tablets
	}
	return nil
}

var File_api_searchnode_v1_searchnode_proto protoreflect.FileDescriptor

const file_api_searchnode_v1_searchnode_proto_rawDesc = "" +
	"\n" +
	"\"api/searchnode/v1/searchnode.proto\x12\x15kitsune.searchnode.v1\"d\n" +
	"\tTabletRef\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x03 \x01(\tR\treplicaId\"\x92\x01\n" +
	"\x12SearchShardRequest\x128\n" +
	"\x06tablet\x18\x01 \x01(\v2 .kitsune.searchnode.v1.TabletRefR\x06tablet\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"B\n" +
	"\tSearchHit\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"a\n" +
	"\x13SearchShardResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x124\n" +
	"\x04hits\x18\x02 \x03(\v2 .kitsune.searchnode.v1.SearchHitR\x04hits\"\x15\n" +
	"\x13TabletStatusRequest\"\xa0\x01\n" +
	"\fTabletStatus\x128\n" +
	"\x06tablet\x18\x01 \x01(\v2 .kitsune.searchnode.v1.TabletRefR\x06tablet\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12'\n" +
	"\x0flast_checkpoint\x18\x04 \x01(\x03R\x0elastCheckpoint\"U\n" +
	"\x14TabletStatusResponse\x12=\n" +
	"\atablets\x18\x01 \x03(\v2#.kitsune.searchnode.v1.TabletStatusR\atablets2\xe2\x01\n" +
	"\x11SearchNodeService\x12d\n" +
	"\vSearchShard\x12).kitsune.searchnode.v1.SearchShardRequest\x1a*.kitsune.searchnode.v1.SearchShardResponse\x12g\n" +
	"\fTabletStatus\x12*.kitsune.searchnode.v1.TabletStatusRequest\x1a+.kitsune.searchnode.v1.TabletStatusResponseB=Z;github.com/cobeo2004/kitsune/api/searchnode/v1;searchnodev1b\x06proto3"

var (
	file_api_searchnode_v1_searchnode_proto_rawDescOnce sync.Once
	file_api_searchnode_v1_searchnode_proto_rawDescData []byte
)

func file_api_searchnode_v1_searchnode_proto_rawDescGZIP() []byte {
	file_api_searchnode_v1_searchnode_proto_rawDescOnce.Do(func() {
		file_api_searchnode_v1_searchnode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_searchnode_v1_searchnode_proto_rawDesc), len(file_api_searchnode_v1_searchnode_proto_rawDesc)))
	})
	return file_api_searchnode_v1_searchnode_proto_rawDescData
}

var file_api_searchnode_v1_searchnode_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_searchnode_v1_searchnode_proto_goTypes = []any{
	(*TabletRef)(nil),            // 0: kitsune.searchnode.v1.TabletRef
	(*SearchShardRequest)(nil),   // 1: kitsune.searchnode.v1.SearchShardRequest
	(*SearchHit)(nil),            // 2: kitsune.searchnode.v1.SearchHit
	(*SearchShardResponse)(nil),  // 3: kitsune.searchnode.v1.SearchShardResponse
	(*TabletStatusRequest)(nil),  // 4: kitsune.searchnode.v1.TabletStatusRequest
	(*TabletStatus)(nil),         // 5: kitsune.searchnode.v1.TabletStatus
	(*TabletStatusResponse)(nil), // 6: kitsune.searchnode.v1.TabletStatusResponse
}
var file_api_searchnode_v1_searchnode_proto_depIdxs = []int32{
	0, // 0: kitsune.searchnode.v1.SearchShardRequest.tablet:type_name -> kitsune.searchnode.v1.TabletRef
	2, // 1: kitsune.searchnode.v1.SearchShardResponse.hits:type_name -> kitsune.searchnode.v1.SearchHit
	0, // 2: kitsune.searchnode.v1.TabletStatus.tablet:type_name -> kitsune.searchnode.v1.TabletRef
	5, // 3: kitsune.searchnode.v1.TabletStatusResponse.tablets:type_name -> kitsune.searchnode.v1.TabletStatus
	1, // 4: kitsune.searchnode.v1.SearchNodeService.SearchShard:input_type -> kitsune.searchnode.v1.SearchShardRequest
	4, // 5: kitsune.searchnode.v1.SearchNodeService.TabletStatus:input_type -> kitsune.searchnode.v1.TabletStatusRequest
	3, // 6: kitsune.searchnode.v1.SearchNodeService.SearchShard:output_type -> kitsune.searchnode.v1.SearchShardResponse
	6, // 7: kitsune.searchnode.v1.SearchNodeService.TabletStatus:output_type -> kitsune.searchnode.v1.TabletStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_searchnode_v1_searchnode_proto_init() }
func file_api_searchnode_v1_searchnode_proto_init() {
	if File_api_searchnode_v1_searchnode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_searchnode_v1_searchnode_proto_rawDesc), len(file_api_searchnode_v1_searchnode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_searchnode_v1_searchnode_proto_goTypes,
		DependencyIndexes: file_api_searchnode_v1_searchnode_proto_depIdxs,
		MessageInfos:      file_api_searchnode_v1_searchnode_proto_msgTypes,
	}.Build()
	File_api_searchnode_v1_searchnode_proto = out.File
	file_api_searchnode_v1_searchnode_proto_goTypes = nil
	file_api_searchnode_v1_searchnode_proto_depIdxs = nil
}
