// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: api/searchnode/v1/searchnode.proto

package searchnodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchNodeService_SearchShard_FullMethodName  = "/kitsune.searchnode.v1.SearchNodeService/SearchShard"
	SearchNodeService_TabletStatus_FullMethodName = "/kitsune.searchnode.v1.SearchNodeService/TabletStatus"
)

// SearchNodeServiceClient is the client API for SearchNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchNodeServiceClient interface {
	SearchShard(ctx context.Context, in *SearchShardRequest, opts ...grpc.CallOption) (*SearchShardResponse, error)
	TabletStatus(ctx context.Context, in *TabletStatusRequest, opts ...grpc.CallOption) (*TabletStatusResponse, error)
}

type searchNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchNodeServiceClient(cc grpc.ClientConnInterface) SearchNodeServiceClient {
	return &searchNodeServiceClient{cc}
}

func (c *searchNodeServiceClient) SearchShard(ctx context.Context, in *SearchShardRequest, opts ...grpc.CallOption) (*SearchShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchShardResponse)
	err := c.cc.Invoke(ctx, SearchNodeService_SearchShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchNodeServiceClient) TabletStatus(ctx context.Context, in *TabletStatusRequest, opts ...grpc.CallOption) (*TabletStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TabletStatusResponse)
	err := c.cc.Invoke(ctx, SearchNodeService_TabletStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchNodeServiceServer is the server API for SearchNodeService service.
// All implementations must embed UnimplementedSearchNodeServiceServer
// for forward compatibility.
type SearchNodeServiceServer interface {
	SearchShard(context.Context, *SearchShardRequest) (*SearchShardResponse, error)
	TabletStatus(context.Context, *TabletStatusRequest) (*TabletStatusResponse, error)
	mustEmbedUnimplementedSearchNodeServiceServer()
}

// UnimplementedSearchNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchNodeServiceServer struct{}

func (UnimplementedSearchNodeServiceServer) SearchShard(context.Context, *SearchShardRequest) (*SearchShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchShard not implemented")
}
func (UnimplementedSearchNodeServiceServer) TabletStatus(context.Context, *TabletStatusRequest) (*TabletStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TabletStatus not implemented")
}
func (UnimplementedSearchNodeServiceServer) mustEmbedUnimplementedSearchNodeServiceServer() {}
func (UnimplementedSearchNodeServiceServer) testEmbeddedByValue()                           {}

// UnsafeSearchNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchNodeServiceServer will
// result in compilation errors.
type UnsafeSearchNodeServiceServer interface {
	mustEmbedUnimplementedSearchNodeServiceServer()
}

func RegisterSearchNodeServiceServer(s grpc.ServiceRegistrar, srv SearchNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchNodeService_ServiceDesc, srv)
}

func _SearchNodeService_SearchShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchNodeServiceServer).SearchShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchNodeService_SearchShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchNodeServiceServer).SearchShard(ctx, req.(*SearchShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchNodeService_TabletStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TabletStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchNodeServiceServer).TabletStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchNodeService_TabletStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchNodeServiceServer).TabletStatus(ctx, req.(*TabletStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchNodeService_ServiceDesc is the grpc.ServiceDesc for SearchNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kitsune.searchnode.v1.SearchNodeService",
	HandlerType: (*SearchNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchShard",
			Handler:    _SearchNodeService_SearchShard_Handler,
		},
		{
			MethodName: "TabletStatus",
			Handler:    _SearchNodeService_TabletStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/searchnode/v1/searchnode.proto",
}
